# Generated by Django 5.0 on 2023-12-31 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
